-- =================================================================
-- SCRIPT PARA CREAR TABLESPACE Y USUARIOS
-- =================================================================

-- Crear tablespace DEVELOPER
CREATE TABLESPACE DEV_ORACLE
    DATAFILE '/opt/oracle/oradata/XE/XEPDB1/dev_oracle.dbf' SIZE 300M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;


-- Consultar que el tablespace DEVELOPER existe
SELECT TABLESPACE_NAME
FROM DBA_TABLESPACES
WHERE TABLESPACE_NAME = 'DEV_ORACLE';


-- Crear usuario ANDRE_DEV en el tablespace DEVELOPER
CREATE USER ANDRE_DEV IDENTIFIED BY AndreDevPass2025
    DEFAULT TABLESPACE DEV_ORACLE
    TEMPORARY TABLESPACE temp;

-- Crear usuario LUIS_DEV en el tablespace DEVELOPER
CREATE USER LUIS_DEV IDENTIFIED BY OracleUserPass2025
    DEFAULT TABLESPACE DEV_ORACLE
    TEMPORARY TABLESPACE temp;

-- Crear rol DEVELOPER
CREATE ROLE DEVELOPER;

-- Privilegios del rol DEVELOPER
GRANT CONNECT, RESOURCE TO DEVELOPER;
GRANT CREATE SESSION TO DEVELOPER;
GRANT CREATE TABLE TO DEVELOPER;
GRANT CREATE VIEW TO DEVELOPER;
GRANT CREATE SEQUENCE TO DEVELOPER;
GRANT CREATE PROCEDURE TO DEVELOPER;
GRANT CREATE ANY SYNONYM TO DEVELOPER;
GRANT UNLIMITED TABLESPACE TO DEVELOPER;

-- Asignar rol a los usuarios
GRANT DEVELOPER TO LUIS_DEV;
GRANT DEVELOPER TO ANDRE_DEV;

-- Ampliar la QUOTA a los usuarios
ALTER USER ANDRE_DEV QUOTA 300M ON DATA;
ALTER USER LUIS_DEV QUOTA 300M ON DATA;

-- Verificar que el usuario ANDRE_DEV existe en el tablespace DEVELOPER
SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'ANDRE_DEV';

-- Verificar que el usuario LUIS_DEV existe en el tablespace DEVELOPER
SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'LUIS_DEV';



