-- Ejecutado por ANDRE_DEV

-- ============================================
-- REVOKE: Revocación de todos los permisos a LUIS
-- Esto elimina los permisos SELECT, INSERT, UPDATE, DELETE y REFERENCES.
-- ============================================

REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON department FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON province FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON district FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON provider FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON client FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON client_user FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON rol FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON user_table FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON transactions FROM LUIS;
REVOKE SELECT, INSERT, UPDATE, DELETE, REFERENCES ON transaction_detail FROM LUIS;

COMMIT;
