-- Ejecutado por ANDRE_DEV

-- ===================================
-- DESACTIVAR RESTRICCIONES Y ELIMINAR TABLAS EXISTENTES
-- ===================================
BEGIN
    FOR c IN (SELECT constraint_name, table_name FROM user_constraints WHERE constraint_type = 'R') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DISABLE CONSTRAINT ' || c.constraint_name;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/
COMMIT;

DECLARE
    table_exists NUMBER;
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables
        WHERE table_name IN (
            'CLIENT_USER', 'CLIENT', 'TRANSACTION_DETAIL', 'TRANSACTIONS',
            'DISTRICT', 'PROVINCE', 'DEPARTMENT', 'PROVIDER', 'USER_TABLE', 'ROL'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
        DBMS_OUTPUT.PUT_LINE('Tabla ' || t.table_name || ' eliminada correctamente');
    END LOOP;
END;
/
COMMIT;

CREATE TABLE department (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL
);

CREATE TABLE province (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  department_id NUMBER NOT NULL,
  name VARCHAR2(100) NOT NULL
);

CREATE TABLE district (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  province_id NUMBER NOT NULL,
  name VARCHAR2(100) NOT NULL
);

CREATE TABLE rol (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  rol VARCHAR2(50) NOT NULL,
  description VARCHAR2(150)
);

CREATE TABLE user_table (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  rol_id NUMBER,
  names VARCHAR2(100),
  last_names VARCHAR2(100),
  email VARCHAR2(100),
  password VARCHAR2(50),
  cellphone VARCHAR2(15),
  doc_type VARCHAR2(15),
  doc_number VARCHAR2(15)
);

CREATE TABLE provider (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  district_id NUMBER,
  name VARCHAR2(100),
  business_type VARCHAR2(50),
  ruc VARCHAR2(20),
  email VARCHAR2(100),
  cellphone VARCHAR2(20),
  address VARCHAR2(200)
);

CREATE TABLE client (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  names VARCHAR2(100),
  last_names VARCHAR2(100),
  cellphone VARCHAR2(15),
  email VARCHAR2(100),
  birth_date DATE,
  doc_type VARCHAR2(10),
  doc_number VARCHAR2(15)
);

CREATE TABLE client_user (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  client_id NUMBER NOT NULL,
  email VARCHAR2(100),
  password VARCHAR2(50)
);

CREATE TABLE transactions (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  client_id NUMBER,
  client_user_id NUMBER,
  user_id NUMBER
);

CREATE TABLE transaction_detail (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  transaction_id NUMBER,
  product_code VARCHAR2(50),
  unitary_price NUMBER(10,2),
  subtotal_trans NUMBER(10,2)
);