-- Ejecutado por ANDRE_DEV

-- ============================================
-- GRANTS: Permisos para el usuario LUIS
-- Se eliminan los comandos de SYNONYM que causaban ORA-01031.
-- ============================================
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON department TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON province TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON district TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON provider TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON client TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON client_user TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON rol TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON user_table TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON transactions TO LUIS;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON transaction_detail TO LUIS;
COMMIT;