-- ==========================
-- RESET DE ESQUEMA ANDRE_DEV
-- ==========================

-- 1. Eliminar tablas hijas antes que las padres (en orden de dependencia)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE transaction_detail CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE transactions CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE client_user CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE client CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE provider CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE user_table CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE rol CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE district CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE province CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE department CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

COMMIT;
