BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE report_detail CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE report CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE product CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE inventory_movement CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

COMMIT;
